name: Build libretro Snes9x WASM

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: latest
        actions-cache-folder: emsdk-cache

    - name: Clone libretro Snes9x
      run: |
        git clone https://github.com/libretro/snes9x.git
        cd snes9x
        git submodule update --init --recursive

    - name: Build libretro core (emscripten)
      run: |
        cd snes9x/libretro
        make \
          platform=emscripten \
          CC=emcc \
          CXX=em++ \
          AR=emar \
          RANLIB=emranlib

    - name: Link WASM + JS
      run: |
        cd snes9x/libretro

        # Rename output file
        mv snes9x_libretro_emscripten.bc libsnes9x.a

        file libsnes9x.a
        head -c 8 libsnes9x.a

        emcc \
        -O3 \
        -s WASM=1 \
        -s LEGACY_RUNTIME=1 \
        -s ALLOW_MEMORY_GROWTH=1 \
        -s ALLOW_TABLE_GROWTH=1 \
        -s ENVIRONMENT=web \
        -s EXPORTED_RUNTIME_METHODS='[
          "addFunction",
          "removeFunction",
          "cwrap",
          "ccall",
          "FS",
          "HEAPU8",
          "HEAPU32",
          "HEAP32"
        ]' \
        -s EXPORTED_FUNCTIONS='[
          "_retro_init",
          "_retro_deinit",
          "_retro_run",
          "_retro_load_game",
          "_retro_unload_game",
          "_retro_set_environment",
          "_retro_set_video_refresh",
          "_retro_set_audio_sample",
          "_retro_set_audio_sample_batch",
          "_retro_set_input_poll",
          "_retro_set_input_state",
          "_malloc",
          "_free"
        ]' \
        -Wl,--whole-archive libsnes9x.a -Wl,--no-whole-archive \
        -o snes9x.js

    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: snes9x-wasm
        path: |
          snes9x/libretro/snes9x.js
          snes9x/libretro/snes9x.wasm
